config/routes.rb
MoralStory::Application.routes.draw do
  devise_for :users

  match "story/follow", :to => "Story#follow"
  match "story/like", :to => "Story#like"
  match "users/follow", :to => "Users#follow"
  
  devise_scope :user do
    match "users/sign_out", :to => "Devise/sessions#destroy"
  end

  resources :pages
  resources :users
  resources :story
  
  match "/search", :to => "Pages#search"
  
  get "users/show"
  
  get "comment/show"
  match "story/comment", :to => "Story#comment"

  get "story/index"
  match "/stories", :to => "Story#index"
  get "story/show"
  get "story/create"
  get "story/new"
  get "story/destroy"
  get "story/upvote"
  get "story/downvote"
  match "/notifications", :to => "Pages#notifications"
  
  default_url_options :host => "localhost:3000"

  root :to => 'pages#index'

end

app/models/story.rb
class Story < ActiveRecord::Base
  attr_accessible :story, :title, :characteristic, :age, :moral, :educational_technique,
                  :score, :parent_story, :user_id, :topic
  
  AGE_GROUPS = ["High School", "College", "Elementary", "Preschool", "Middle School", "General Public"]
  TECHNIQUES = ["Lecture", "Discussion", "Hands On"]
  
  #validations
  #no values can be empty except characteristics
  
  def author
    User.find(self.user_id)
  end
  
  def related_by_age
    Story.find_all_by_age(self.age, :order => "score DESC", :limit => 5)
  end
  
  def related_by_topic
    Story.find_all_by_topic(self.topic, :order => "score DESC", :limit => 5)
  end
  
  def related_by_technique
    Story.find_all_by_educational_technique(self.educational_technique, :order => "score DESC", :limit => 5)
  end
  
  def related_by_author
    Story.find_all_by_user_id(self.user_id, :order => "score DESC", :limit => 5)
  end
  
  def liked_by(user)
    !Like.find_by_story_id_and_user_id(self.id, user.id).nil?
  end
  
  def likes
    Like.first(:select => "count(*) AS size", :conditions => "story_id = '#{self.id}'").size.to_i
  end
  
  def followers
    User.all(:joins => "JOIN subscriptions ON user_id = users.id",
              :conditions => ["subscribed_to = 'stories' AND target_id = ?", self.id])
  end
end

app/controllers/story_controller.rb
class StoryController < ApplicationController
  before_filter :authenticate_user!, :only => [:create, :new, :destroy, :upvote, :downvote]
  
  def index
    @stories = Story.paginate(:page => params[:page], :per_page => 15)
  end

  def show
    @story = Story.find(params[:id])
    @new_comment = Comment.new
    @comments = Comment.find_all_by_comment_on_table_and_comment_on_id("stories", @story, :order => "created_at")
    unless params[:comment].nil? || params[:comment] == ""
      @important_comment = Comment.find(params[:comment])
      
      #set the Notification as viewed
      note = nil
      if params[:reply]
        note = Notification.find_by_user_id_and_target_id_and_caused_by(@user.id, params[:reply_id], "comment reply")
      else
        note = Notification.find_by_user_id_and_target_id_and_caused_by(@user.id, @important_comment.id, "new comment")
      end
      unless note.nil?
        note.viewed = true
        note.save
      end
    end
    
    if signed_in?
      #remove any notifications the user had for this story
      notes = Notification.all(:conditions => ["user_id = ? AND target_id = ? AND caused_by LIKE '%story%'", @user.id, @story.id])
      notes.each { |note|
        note.viewed = true
        note.save
      }
    end
  end

  def create
    @story = Story.create(:user_id => params[:story][:user_id],
                          :title => params[:story][:title],
                          :story => params[:story][:story].html_safe,
                          :age => params[:story][:age],
                          :topic => params[:story][:topic],
                          :educational_technique => params[:story][:educational_technique],
                          :parent_story => params[:story][:parent_id],
                          :moral => params[:story][:moral],
                          :score => 0)
    Subscription.create(:user_id => params[:story][:user_id],
                        :subscribed_to => "stories",
                        :target_id => @story.id)
    
    #notify all followers of the user that created this story
    main_user = User.find(params[:story][:user_id])
    
    main_user.followers.each { |user|
      Notification.create(:user_id => user.id,
                          :caused_by => "user story",
                          :target_id => @story.id)
    }
    
    if !params[:story][:parent_id].nil? && params[:story][:parent_id] != ""
      #Notify everyone following the original story
      original_story = Story.find(params[:story][:parent_id])
      
      original_story.followers.each { |user|
        unless original_story.user_id == user.id
          Notification.create(:user_id => user.id,
                              :caused_by => "related story",
                              :target_id => @story.id)
        end
      }
    end
    
    if @story.save
      redirect_to(story_path(@story), :notice => 'Your story was successfully created.')
    else
      render :action => "new"
    end
  end

  def new
    @story = Story.new
    @user = current_user
  end

  def destroy
  end

  def like
    story = Story.find(params[:story])
    if story.liked_by(@user)
      like = Like.find_by_story_id_and_user_id(story.id, @user.id)
      Like.delete(like)
    else
      Like.create(:user_id => @user.id,
                  :story_id => story.id)
    end
    redirect_to :back
  end
  
  def comment
    if params[:comment][:content].length > 1
      #create the comment
      comment = Comment.create(params[:comment])
      
      #if the comment was a reply to another comment
      if params[:comment][:comment_on_table] == "comments"
        
        #subscribe the user to the original comment, unless they are already following it
        comment_replied_to = Comment.find(params[:comment][:comment_on_id])
        unless @user.is_following(comment_replied_to)
          Subscription.create(:user_id => params[:comment][:user_id],
                            :subscribed_to => "comments",
                            :target_id => comment.id)
        end
                
        comment_replied_to.followers.each{ |user|
          unless comment_replied_to.user_id = user.id
            Notification.create(:user_id => user.id,
                                :caused_by => "comment reply",
                                :target_id => comment.id)
          end
        }
        
      else #else it was a reply to a story
        Subscription.create(:user_id => params[:comment][:user_id],
                            :subscribed_to => "comments",
                            :target_id => comment.id)
        
        #Notify all the followers of this story
        story = Story.find(params[:comment][:comment_on_id])
        
        story.followers.each{ |user|
          unless story.user_id == user.id
            Notification.create(:user_id => user.id,
                                :from => "new comment",
                                :target_id => comment.id)
          end
        }
        
      end
    end
    redirect_to :back
  end
  
  def follow
    story = Story.find(params[:story])
    if @user.is_following(story)
      subscription = Subscription.find_by_user_id_and_subscribed_to_and_target_id(@user.id, "stories", story.id)
      Subscription.delete(subscription)
      flash.now[:notice] = "You are no longer following this story."
    else
      Subscription.create(:user_id => @user.id,
                          :subscribed_to => "stories",
                          :target_id => story.id)
      flash.now[:notice] = "You are now following this story."
    end
    redirect_to :back
  end

end

app/helpers/story_helper.rb
module StoryHelper
end

app/views/story/_form.html.erb
<%= form_for @story, :url => "/story" do |f| %>
<table>
  <tr>
    <td>
      <%= f.label "Title:" %>
    </td>
  </tr>
  <tr>
    <td>
      <%= f.text_field :title %>
    </td>
  </tr>
  <tr>
    <td>
      <%= f.label "Moral:" %>
    </td>
  </tr>
  <tr>
    <td>
      <%= f.text_field :moral %>
    </td>
  </tr>
  <tr>
    <td>
      <%= f.label "Story:" %>
    </td>
  </tr>
  <tr>
    <td>
      <%= f.text_area :story, :class => "story_text_area" %>
    </td>
  </tr>
  <tr>
    <td>
      <%= f.label "Age group:" %>
    </td>
  </tr>
  <tr>
    <td>
      <%= select(:story, :age, Story::AGE_GROUPS, {}) %>
    </td>
  </tr>
  <tr>
    <td>
      <%= f.label "Topic:" %>
    </td>
  </tr>
  <tr>
    <td>
      <%= f.text_field :topic %>
    </td>
  </tr>
  <tr>
    <td>
      <%= f.label "Educational Technique:" %>
    </td>
  </tr>
  <tr>
    <td>
      <%= select(:story, :educational_technique, Story::TECHNIQUES, {}) %>
    </td>
  </tr>
  <%= f.hidden_field :parent_story, :value => params[:from] %>
  <%= f.hidden_field :user_id, :value => @user.id %>
  <tr>
    <td>
      <%= f.submit "Create", :class => "btn-inverse btn" %>
    </td>
  </tr>
</table>
  
<% end %>

app/views/story/create.html.erb
<h1>Story#create</h1>
<p>Find me in app/views/story/create.html.erb</p>

app/views/story/index.html.erb
<div class="digg_pagination span9">
  <h1>Story list: </h1>
  <table id="story_list" class="border1">
    <thead>
      <th class="border1">
        Title
      </th>
      <th class="border1">
        Author
      </th>
    </thead>
  <% @stories.each { |story| %>
    <tr>
      <td class="border1"><%= link_to story.title, story_path(story) %></td>
      <td class="border1"><%= link_to story.author.name, user_path(story.author) %></td>
    </tr>
  <% } %>
  </table>  
  <%= will_paginate @stories %>
</div>

app/views/story/new.html.erb
<%= render 'form' %>

app/views/story/show.html.erb
<%= content_for :head do %>
  <script type="text/javascript">
    $(document).ready(function()
    {
      replyToComment = function(comment_id, story_id, reply_id)
      {
        if ($('#submit_comment_button').attr("value") == "Comment")
        {
          $('.hidden_table_field').attr("value", "comments");
          $('.hidden_id_field').attr("value", comment_id);
          $('#alternate_cancel_reply_link').attr("href",
                                                "javascript:replyToComment(" + comment_id + "," + story_id +")");
          $('#alternate_cancel_reply_link').removeClass("hide");
          if (reply_id >= 0)
          {
            $('div.reply_link a.reply_to_' + reply_id).html("Cancel Reply");
          }
          else
          {
            $('div.reply_link a.reply_to_' + comment_id).html("Cancel Reply");
          }
          $('#submit_comment_button').attr("value", "Reply");
        }
        else
        {
          $('.hidden_table_field').attr("value", "stories");
          $('.hidden_id_field').attr("value", story_id);
          $('#submit_comment_button').attr("value", "Comment");
          $('#alternate_cancel_reply_link').addClass("hide");
          if (reply_id >= 0)
          {
            $('div.reply_link a.reply_to_' + reply_id).html("Reply");
          }
          else
          {
            $('div.reply_link a.reply_to_' + comment_id).html("Reply");
          }
        }
      }
    });
  </script>
<% end %>

<div id="story_show_information" class="span6" style="width: span2">
  <br/>
  <div>
    <div id="story_show_title">
      <h3><%= @story.title %></h3>
    </div>
    <% if signed_in? %>
      <div>
        <% if @user.is_following(@story) %>
          <%= link_to "Unfollow", "/story/follow?story=" + @story.id.to_s, :class => "btn-mini btn btn-danger", :method => :POST %>
        <% else %>
          <%= link_to "Follow", "/story/follow?story=" + @story.id.to_s, :class => "btn-mini btn btn-success", :method => :POST%>
        <% end %>
      </div>
    <% end %>
    <div id="story_show_author">
      Author: 
      <% if @story.author.show_name %>
        <%= link_to @story.author.name, user_path(@story.author) %>
      <% else %>
        <%= link_to @story.author.username, user_path(@story.author) %>
      <% end %>
    </div>
    <div id="story_show_details" class="span6">
      <% if !@story.age.nil? %>
        <div id="story_show_age">
          Age: <%= @story.age %>
        </div>
      <% end %>
      <% if !@story.topic.nil? %>
        <div id="story_show_topic">
          Topic: <%= @story.topic %>
        </div>
      <% end %>
      <% if !@story.educational_technique.nil? %>
        <div id="story_show_technique">
          Educational technique: <%= @story.educational_technique %>
        </div>
      <% end %>
    </div>
  </div>
  <div id="story_show_content" class="span6 border1">
    <%= sanitize @story.story.gsub("\n", "<br/>"), :tags => %w(i b u br ol ul li) %>
  </div>
  <div id="story_show_like_button">
    <% if signed_in? %>
      <% if @story.liked_by(@user) %>
        <%= link_to "Like", story_like_path + "?story=" + @story.id.to_s, :class => "btn btn-success", :method => :POST %>
      <% else %>
        <%= link_to "Like", story_like_path + "?story=" + @story.id.to_s, :class => "btn", :method => :POST %>
      <% end %>
    <% else %>
      <p class="btn" disabled="true">Like</p>
    <% end %>
    <div class="right">
      <% if signed_in? && @story.liked_by(@user) %>
        <% if @story.likes > 1 %>
          You, and <%= (@story.likes - 1).to_s %> other people like this story.
        <% else %>
          You like this story.
        <% end %>
      <% else %>
        <%= @story.likes %> people like this story.
      <% end %>
    </div>
  </div>
  
  <div>
    <% if user_signed_in? %>
      <%= form_for @new_comment, :url => "/story/comment" do |f| %>
        <%= f.hidden_field :user_id, :value => current_user.id %>
        <%= f.hidden_field :comment_on_table, :value => "stories", :class => "hidden_table_field" %>
        <%= f.hidden_field :comment_on_id, :value => @story.id.to_s, :class => "hidden_id_field" %>
        <%= f.text_area :content, :class => "story_show_comment_text_area" %>
        <br/>
        <%= f.submit "Comment", :id => "submit_comment_button", :class => "btn btn-primary" %>
        <a class="hide" id="alternate_cancel_reply_link" href="">Cancel Reply</a>
      <% end %>
    <% end %>
  </div>
  <% unless @important_comment.nil? %>
    <div id="story_show_important_comment" class="span6 border1">
      <div class="comment border1">
        <div>
        <% user = @important_comment.user %>
        <% if user.show_name %>
          <%= user.name %>:
        <% else %>
          <%= user.username %>:
        <% end %>
        </div>
        <div>
        <%= @important_comment.content %>
        </div>
        <div class="reply_link">
          <% if signed_in? %>
            <%= link_to "Reply", "javascript:replyToComment(#{@important_comment.id},#{@story.id},-1);", :class => "reply_to_" + @important_comment.id.to_s %>
          <% end %>
        </div>
        <% unless @important_comment.replies.nil? %>
          <% @important_comment.replies.each { |reply| %>
            <div class="reply border1">
              <% user = reply.user %>
              <div>
                <% if user.show_name %>
                  <%= user.name %>:
                <% else %>
                  <%= user.username %>:
                <% end %>
              </div>
              <div>
                <%= reply.content %>
              </div>
              <div class="reply_link">
                <% if signed_in? %>
                  <%= link_to "Reply", "javascript:replyToComment(#{@important_comment.id},#{@story.id},#{reply.id});", :class => "reply_to_" + reply.id.to_s %>
                <% end %>
              </div>
            </div>
          <% } %>
        <% end %>
      </div>
    </div>
  <% end %>
  <div id="story_show_comments" class="span6 border1">
    <% if !@comments.nil? && @comments.size > 0 %>
      <% @comments.each { |comment| %>
        <% if @important_comment.nil? || comment.id != @important_comment.id %>
          <div class="comment border1">
            <div>
            <% user = comment.user %>
            <% if user.show_name %>
              <%= user.name %>:
            <% else %>
              <%= user.username %>:
            <% end %>
            </div>
            <div>
            <%= comment.content %>
            </div>
            <div class="reply_link">
              <% if signed_in? %>
                <%= link_to "Reply", "javascript:replyToComment(#{comment.id},#{@story.id},-1);", :class => "reply_to_" + comment.id.to_s %>
              <% end %>
            </div>
            <% unless comment.replies.nil? %>
              <% comment.replies.each { |reply| %>
                <div class="reply border1">
                  <% user = reply.user %>
                  <div>
                    <% if user.show_name %>
                      <%= user.name %>:
                    <% else %>
                      <%= user.username %>:
                    <% end %>
                  </div>
                  <div>
                    <%= reply.content %>
                  </div>
                  <div class="reply_link">
                    <% if signed_in? %>
                      <%= link_to "Reply", "javascript:replyToComment(#{comment.id},#{@story.id},#{reply.id});", :class => "reply_to_" + reply.id.to_s %>
                    <% end %>
                  </div>
                </div>
              <% } %>
            <% end %>
          </div>
        <% end %>
      <% } %>
    <% else %>
      <p class="large_gray_text">
        There are no comments on this story yet.<br/>Submit your own comment above!
      </p>
    <% end %>
  </div>
</div>
  
<div id="story_show_related" class="span3">
  <%= link_to "Submit a related story", new_story_path + "?from=" + @story.id.to_s, :class => "btn btn-success" %>
  <table id="stories_related_by_age" class="border1">
    <thead>
      <th class="border1">
        Stories with a similar age group:
      </th>
    </thead>
    <% @story.related_by_age.each { |related| %>
      <tr>
        <td class="border1">
          <%= link_to related.title, story_path(related) %>
        </td>
      </tr>
    <% } %>
  </table>
  <br/>
  <table id="stories_related_by_topic" class="border1">
    <thead>
      <th class="border1">
        Stories with a similar topic:
      </th>
    </thead>
    <% @story.related_by_topic.each { |related| %>
      <tr>
        <td class="border1">
          <%= link_to related.title, story_path(related) %>
        </td>
      </tr>
    <% } %>
  </table>
  <br/>
  <table id="stories_related_by_author" class="border1">
    <thead>
      <th class="border1">
        Other stories by this author:
      </th>
    </thead>
    <% @story.related_by_author.each { |related| %>
      <tr>
        <td class="border1">
          <%= link_to related.title, story_path(related) %>
        </td>
      </tr>
    <% } %>
  </table>
</div>