config/routes.rb
MoralStory::Application.routes.draw do
  devise_for :users

  match "story/follow", :to => "Story#follow"
  match "story/like", :to => "Story#like"
  match "users/follow", :to => "Users#follow"
  
  devise_scope :user do
    match "users/sign_out", :to => "Devise/sessions#destroy"
  end

  resources :pages
  resources :users
  resources :story
  
  match "/search", :to => "Pages#search"
  
  get "users/show"
  
  get "comment/show"
  match "story/comment", :to => "Story#comment"

  get "story/index"
  match "/stories", :to => "Story#index"
  get "story/show"
  get "story/create"
  get "story/new"
  get "story/destroy"
  get "story/upvote"
  get "story/downvote"
  match "/notifications", :to => "Pages#notifications"
  
  default_url_options :host => "localhost:3000"

  root :to => 'pages#index'

end

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/index.html.erb
<div class="span9">
  <div>
    This will be the homepage for the site.
  </div>
</div>

app/views/pages/notifications.html.erb
<div class="span9">
  <div class="span6 border1">
    <table id="notifications_table">
      <% @notifications.each { |notification| %>
        <% related_user = notification.from_user %>
        <tr>
          <td class="border1 notification_description">
            <% if notification.caused_by == "user story" %>
              <% if related_user.show_name %>
                <%= link_to related_user.name, user_path(related_user) %>
              <% else %>
                <%= link_to related_user.username, user_path(related_user) %>
              <% end %> has created a new story!
            <% elsif notification.caused_by == "related story" %>
              <% if related_user.show_name %>
                <%= link_to related_user.name, user_path(related_user) %>
              <% else %>
                <%= link_to related_user.username, user_path(related_user) %>
              <% end %> has submitted a story related to a story you follow!
            <% elsif notification.caused_by == "comment reply" %>
              <% if related_user.show_name %>
                <%= link_to related_user.name, user_path(related_user) %>
              <% else %>
                <%= link_to related_user.username, user_path(related_user) %>
              <% end %> has replied to one of your comments!
            <% elsif notification.caused_by == "new comment" %>
              <% if related_user.show_name %>
                <%= link_to related_user.name, user_path(related_user) %>
              <% else %>
                <%= link_to related_user.username, user_path(related_user) %>
              <% end %> has commented on a story you follow!
            <% end %>
          </td>
          <td class="border1 notification_link">
            <%= link_to "Check it out!", notification.link %>
          </td>
        </tr>
      <% } %>
    </table>
  <div>
</div>

app/views/pages/search.html.erb
<table>
  <% if params[:type] == "users" %>
    <% @results.each { |result| %>
      <tr>
        <td class="border1 search_results center">
          <%= image_tag result.gravatar_url %>
        </td>
          
        <td class="border1 search_results center">
          <%= link_to result.username, user_path(result) %>
        </td>
      </tr>
    <% } %>
  <% else %>
    <thead>
      <tr>
        <th class="border1 search_results">Story</th>
        <th class="border1 search_results">Author</th>
        <th class="border1 search_results">Content</th>
      </tr>
    </thead>
    <% @results.each { |result| %>
      <tr>
        <td class="border1 search_results center">
          <%= link_to result.title, story_path(result) %>
        </td>
        <td class="border1 search_results center">
          <%= result.author.username %>
        </td>
        <td class="border1 search_results">
          <%= result.story[0..60]%> ...
        </td>
      </tr>
    <% }%>
  <% end %>
</table>

app/views/pages/signin.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/signin.html.erb</p>

app/views/pages/signup.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/signup.html.erb</p>