config/routes.rb
MoralStory::Application.routes.draw do
  devise_for :users

  match "story/follow", :to => "Story#follow"
  match "story/like", :to => "Story#like"
  match "users/follow", :to => "Users#follow"
  
  devise_scope :user do
    match "users/sign_out", :to => "Devise/sessions#destroy"
  end

  resources :pages
  resources :users
  resources :story
  
  match "/search", :to => "Pages#search"
  
  get "users/show"
  
  get "comment/show"
  match "story/comment", :to => "Story#comment"

  get "story/index"
  match "/stories", :to => "Story#index"
  get "story/show"
  get "story/create"
  get "story/new"
  get "story/destroy"
  get "story/upvote"
  get "story/downvote"
  match "/notifications", :to => "Pages#notifications"
  
  default_url_options :host => "localhost:3000"

  root :to => 'pages#index'

end

app/views/layouts/_header.html.erb
<header class="span9">
  <div id="header_logo">
    <%= link_to image_tag("rails.png"), "/" %>
  </div>
  <div id="header_search_bar">
    <div>
      <form method="get" action="/search">
        <input id="searchbar" name="query" type="text"/>
        <select class="searchbar_dropdown" name="type">
          <option value="users">Users</option>
          <option value="title" selected="true">by Title</option>
          <option value="age">by Age</option>
          <option value="topic">by Topic</option>
          <option value="educational_technique">by Technique</option>
        </select>
      </form>
    </div>
    <div id="header_nav_bar">
      <nav>
      <ul class="small_text">
        <li><%= link_to "Home", root_path %></li>
        <li>|</li>
        <%= link_to "Stories", stories_path %>
        <% if signed_in? %>
          <li>|</li>
          <% if (@user.new_notifications.count) > 1 %>
            <li><%= link_to @user.new_notifications.count.to_s + " new notifications", "/notifications", :class => "notification_text" %></li>
          <% elsif (@user.new_notifications.count) == 1 %>
            <li><%= link_to "1 new notification", "/notifications", :class => "notification_text" %></li>
          <% else %>
            <li><%= link_to "0 new notifications", "/notifications" %></li>
          <% end %>
          <li>|</li>
          <li><%= link_to "Submit your own story!", new_story_path %></li>
        <% end %>
      </ul>
      </nav>
    </div>
  </div>
  <div id="header_profile_info">
    <% if signed_in? %>
      <table>
        <tr>
          <td>
            Signed in as <%= link_to current_user.email, user_path(current_user) %><br/>
          </td>
          <td rowspan="2">
            <%= image_tag current_user.gravatar_url, :class => "header_user_avatar" %>
          </td>
        </tr>
        <tr>
          <td>
            Not you? <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
          </td>
        </tr>
      </table>
    <% else %>
      <%= link_to "Sign in", new_user_session_path %><br/>
      Don't have an account? <%= link_to "Sign up here", new_user_registration_path %>
    <% end %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<title>Moral Story <%= @title.nil? ? "" : "| " + @title %></title>
<html>
  <head>
    <%= stylesheet_link_tag "bootstrap_and_overrides" %>
    <%= stylesheet_link_tag "bootstrap" %>
    <%= stylesheet_link_tag "bootstrap-responsive" %>
    <%= stylesheet_link_tag :application %>
    
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
    <% if ENV["RAILS_ENV"] == "development" %>
      <%= javascript_include_tag "rails" %>
    <% else %>
      <script src="/public/javascripts/rails.js" type="text/javascript"></script>
    <% end %>
    <%#= javascript_include_tag "javascripts/bootstrap-carousel" %>
    <%#= javascript_include_tag "javascripts/bootstrap-collapse" %>
    <%#= javascript_include_tag "javascripts/bootstrap-modal" %>
    <%#= javascript_include_tag "javascripts/bootstrap-tabs" %>
    <%#= javascript_include_tag "javascripts/bootstrap-tooltip" %>
    <%#= javascript_include_tag "javascripts/bootstrap-transition" %>
    
    <%= csrf_meta_tags %>
    
    <%= yield :head %>
  </head>
  <body id="application_background">
    <div id="application_page" class="container span12">
      <div id="application_header">
        <%= render "layouts/header" %>
      </div>
      <div id="application_content">      
        <%= yield %>
      </div>
    </div>
  </body>
</html>